name: 'Pull request dependency checkout'
description: 'This action checks if there is a pull request in the repo with the same title.'
author: 'Sebastian Reimers'
branding:
  icon: activity
  color: gray-dark
inputs:
  repo:
    description: 'git repo dependency to checkout'
    required: true
  name:
    required: true
  secret:
    required: true
  working-directory:
    required: false
    default: '.'
runs:
  using: "composite"
  steps: 
    - name: checkout 
      run: |
        pr_title=$(gh pr view $PR_NUMBER -q .title --json title || echo 'no_pull_request_found')
        cd ${{ inputs.working-directory }} && git clone ${{ inputs.repo }} ${{ inputs.name }} && cd ${{ inputs.name }}
        pr_dependency=$(gh pr list -S "$pr_title in:title" -q ".[] .number" --json number)
        [ -n "$pr_dependency" ] && gh pr checkout $pr_dependency || true
      shell: bash -e {0}
      env:
        PR_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.secret }}
